Support --metadata flag

diff --git a/update-stack b/update-stack
--- a/update-stack
+++ b/update-stack
@@ -5,6 +5,9 @@ set -x
 
 logfile=$(mktemp)
 lambdazip=$(readlink -m package.zip)
+db_paths=()
+dbfiles=
+EXTERNAL=${EXTERNAL:-0}
 
 # Per https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html,
 # the total unzipped size of the deployment package, including layers, must be
@@ -51,7 +54,7 @@ create_or_update_stack() {
   shift
 
   if ! stack_exists "${stack_name}"; then
-    aws cloudformation create-stack --stack-name="${stack_name}" "$@" 
+    aws cloudformation create-stack --stack-name="${stack_name}" "$@"
     aws cloudformation wait stack-create-complete --stack-name="${stack_name}"
   else
     if aws cloudformation update-stack --stack-name="${stack_name}" "$@" |& tee "${logfile}"; then
@@ -77,21 +80,38 @@ create_lambda_zip() {
   popd
 }
 
-main() {
-  stack_name=${1:?must provide CloudFormation stack name}
-  shift
+parse_opts() {
+  local db_size=0 size file
 
-  EXTERNAL=${EXTERNAL:-0}
-  db_size=0
-  dbfiles=
+  rm -f app/metadata.json
+  rm -f app/config.txt
 
-  if [ "$#" -eq 0 ]; then
+  while [ "$#" -gt 0 ]; do
+    case "$1" in
+      -m|--metadata)
+        shift
+        file=${1:?error: --metadata requires file argument}
+        if [ ! -e "${file}" ]; then
+          echo "error: --metadata points to non-existent file ${file}" > /dev/stderr
+          exit 2
+        fi
+
+        cp "${file}" app/metadata.json
+        ;;
+      *)
+        db_paths+=("$1")
+        ;;
+    esac
+    shift
+  done
+
+  if [ "${#db_paths[@]}" -eq 0 ]; then
     echo "error: must specify at least one database" > /dev/stderr
     exit 1
   fi
 
   # All the database files passed must exist.
-  for db in "$@"; do
+  for db in "${db_paths[@]}"; do
     if [ ! -e "${db}" ]; then
       echo "error: cannot find database ${db}" > /dev/stderr
       exit 2
@@ -113,11 +133,18 @@ main() {
     echo "info: EXTERNAL=0 but total size of DBs is ${db_size}; falling back to EXTERNAL=1" > /dev/stderr
     EXTERNAL=1
   fi
+}
+
+main() {
+  stack_name=${1:?must provide CloudFormation stack name}
+  shift
+
+  parse_opts "$@"
 
   create_lambda_zip
 
   if [ "${EXTERNAL}" == "0" ]; then
-    for db in "$@"; do
+    for db in "${db_paths[@]}"; do
       dir=$(dirname "${db}")
       pushd "${dir}"
       zip --quiet "${lambdazip}" "$(basename "${db}")"
@@ -146,7 +173,7 @@ main() {
     --template-body=file://stack-lambda.yaml
 
   if [ "${EXTERNAL}" == "1" ]; then
-    for db in "$@"; do
+    for db in "${db_paths[@]}"; do
       s3cp "${db}" s3://"${bucket}"/"$(basename "${db}")"
     done
   fi
